package com.aci.feature.bible

import com.aci.core.domain.enum.Language

/** UI labels for the Bible screens, selected by the in-app language picker. */
internal data class BibleStrings(
    val holyBible: String,
    val searchTheBible: String,
    val bookmarksAndNotes: String,
    val oldTestament: String,
    val newTestament: String,
    val booksCount: (Int) -> String,
    val chaptersCount: (Int) -> String,
    val selectAChapter: String,
    val previous: String,
    val next: String,
    val fontSize: String,
    val addNote: String,
    val bookmark: String,
    val readingPlanTitle: String,
    val readingPlanBlurb: String,
    val startPlan: String,
    val resetPlan: String,
    val dayOf: (Int, Int) -> String,
    val daysCompleted: (Int, Int) -> String,
    val daysBehind: (Int) -> String,
    val onTrack: String,
    val planFinished: String,
    val todaysReading: String,
    val completedOn: (String) -> String,
    val completedLabel: String,
    val missedLabel: String,
    val todayLabel: String,
    val chaptersReadOf: (Int, Int) -> String,
    val playAudio: String,
    val stopAudio: String,
    val audioUnavailable: String,
    val autoProgressHint: String,
    val signInToTrack: String,
    val signInToTrackBlurb: String,
    val signInCta: String
)

private val english = BibleStrings(
    holyBible = "Holy Bible",
    searchTheBible = "Search the Bible",
    bookmarksAndNotes = "My Bookmarks & Notes",
    oldTestament = "Old Testament",
    newTestament = "New Testament",
    booksCount = { "$it books" },
    chaptersCount = { "$it chapters" },
    selectAChapter = "Select a chapter",
    previous = "Previous",
    next = "Next",
    fontSize = "Font size",
    addNote = "Add note",
    bookmark = "Bookmark",
    readingPlanTitle = "365-Day Bible Reading Plan",
    readingPlanBlurb = "Read the whole Bible in a year — about three chapters a day, Genesis to Revelation.",
    startPlan = "Start Plan",
    resetPlan = "Reset Plan",
    dayOf = { day, total -> "Day $day of $total" },
    daysCompleted = { done, total -> "$done of $total days completed" },
    daysBehind = { "$it days to catch up" },
    onTrack = "On track",
    planFinished = "Plan complete — the whole Bible in a year.",
    todaysReading = "Today's Reading",
    completedOn = { "Completed on $it" },
    completedLabel = "Completed",
    missedLabel = "Not yet read",
    todayLabel = "Today",
    chaptersReadOf = { read, total -> "$read of $total chapters read" },
    playAudio = "Listen to this chapter",
    stopAudio = "Stop audio",
    audioUnavailable = "Audio isn't available for this language on this device. Install the voice in Android Settings › Text-to-speech.",
    autoProgressHint = "Days complete themselves as you read or listen to each chapter.",
    signInToTrack = "Sign in to track your progress",
    signInToTrackBlurb = "Anyone can follow the plan. Register or log in to save which chapters you've read.",
    signInCta = "Register / Login"
)

private val tamil = BibleStrings(
    holyBible = "பரிசுத்த வேதாகமம்",
    searchTheBible = "வேதாகமத்தில் தேடு",
    bookmarksAndNotes = "எனது புத்தகக் குறிகள் & குறிப்புகள்",
    oldTestament = "பழைய ஏற்பாடு",
    newTestament = "புதிய ஏற்பாடு",
    booksCount = { "$it புத்தகங்கள்" },
    chaptersCount = { "$it அதிகாரங்கள்" },
    selectAChapter = "ஒரு அதிகாரத்தைத் தேர்ந்தெடுக்கவும்",
    previous = "முந்தையது",
    next = "அடுத்தது",
    fontSize = "எழுத்து அளவு",
    addNote = "குறிப்பு சேர்",
    bookmark = "புத்தகக் குறி",
    readingPlanTitle = "365 நாள் வேதாகம வாசிப்புத் திட்டம்",
    readingPlanBlurb = "ஒரு வருடத்தில் முழு வேதாகமத்தையும் வாசியுங்கள் — ஒரு நாளைக்கு சுமார் மூன்று அதிகாரங்கள்.",
    startPlan = "திட்டத்தைத் தொடங்கு",
    resetPlan = "திட்டத்தை மீட்டமை",
    dayOf = { day, total -> "நாள் $day / $total" },
    daysCompleted = { done, total -> "$total நாட்களில் $done முடிந்தது" },
    daysBehind = { "$it நாட்கள் பாக்கி" },
    onTrack = "சரியான பாதையில்",
    planFinished = "திட்டம் நிறைவடைந்தது — ஒரு வருடத்தில் முழு வேதாகமம்.",
    todaysReading = "இன்றைய வாசிப்பு",
    completedOn = { "$it அன்று முடிந்தது" },
    completedLabel = "முடிந்தது",
    missedLabel = "இன்னும் வாசிக்கவில்லை",
    todayLabel = "இன்று",
    chaptersReadOf = { read, total -> "$total அதிகாரங்களில் $read வாசித்தாயிற்று" },
    playAudio = "இந்த அதிகாரத்தைக் கேட்க",
    stopAudio = "ஒலியை நிறுத்து",
    audioUnavailable = "இந்தச் சாதனத்தில் இந்த மொழிக்கு ஒலி வசதி இல்லை. Android அமைப்புகள் › Text-to-speech இல் குரலை நிறுவவும்.",
    autoProgressHint = "ஒவ்வொரு அதிகாரத்தையும் வாசிக்கும்போது அல்லது கேட்கும்போது நாட்கள் தானாகவே முடிவடையும்.",
    signInToTrack = "முன்னேற்றத்தைப் பதிவு செய்ய உள்நுழையவும்",
    signInToTrackBlurb = "இந்தத் திட்டத்தை யார் வேண்டுமானாலும் பின்பற்றலாம். நீங்கள் வாசித்த அதிகாரங்களைச் சேமிக்க பதிவு செய்யுங்கள் அல்லது உள்நுழையுங்கள்.",
    signInCta = "பதிவு / உள்நுழைவு"
)

private val telugu = BibleStrings(
    holyBible = "పరిశుద్ధ గ్రంథము",
    searchTheBible = "బైబిల్‌లో వెతకండి",
    bookmarksAndNotes = "నా బుక్‌మార్క్‌లు & గమనికలు",
    oldTestament = "పాత నిబంధన",
    newTestament = "కొత్త నిబంధన",
    booksCount = { "$it పుస్తకాలు" },
    chaptersCount = { "$it అధ్యాయాలు" },
    selectAChapter = "ఒక అధ్యాయాన్ని ఎంచుకోండి",
    previous = "మునుపటి",
    next = "తదుపరి",
    fontSize = "అక్షర పరిమాణం",
    addNote = "గమనిక జోడించు",
    bookmark = "బుక్‌మార్క్",
    readingPlanTitle = "365 రోజుల బైబిల్ పఠన ప్రణాళిక",
    readingPlanBlurb = "ఒక సంవత్సరంలో బైబిల్ మొత్తం చదవండి — రోజుకు సుమారు మూడు అధ్యాయాలు.",
    startPlan = "ప్రణాళికను ప్రారంభించండి",
    resetPlan = "ప్రణాళికను రీసెట్ చేయండి",
    dayOf = { day, total -> "రోజు $day / $total" },
    daysCompleted = { done, total -> "$total రోజుల్లో $done పూర్తయ్యాయి" },
    daysBehind = { "$it రోజులు బాకీ" },
    onTrack = "సరైన దారిలో",
    planFinished = "ప్రణాళిక పూర్తయింది — ఒక సంవత్సరంలో బైబిల్ మొత్తం.",
    todaysReading = "నేటి పఠనం",
    completedOn = { "$it న పూర్తయింది" },
    completedLabel = "పూర్తయింది",
    missedLabel = "ఇంకా చదవలేదు",
    todayLabel = "ఈ రోజు",
    chaptersReadOf = { read, total -> "$total అధ్యాయాల్లో $read చదివారు" },
    playAudio = "ఈ అధ్యాయాన్ని వినండి",
    stopAudio = "ఆడియో ఆపండి",
    audioUnavailable = "ఈ పరికరంలో ఈ భాషకు ఆడియో అందుబాటులో లేదు. Android సెట్టింగ్‌లు › Text-to-speech లో వాయిస్‌ను ఇన్‌స్టాల్ చేయండి.",
    autoProgressHint = "ప్రతి అధ్యాయాన్ని చదివినప్పుడు లేదా విన్నప్పుడు రోజులు వాటంతట అవే పూర్తవుతాయి.",
    signInToTrack = "పురోగతిని ట్రాక్ చేయడానికి సైన్ ఇన్ చేయండి",
    signInToTrackBlurb = "ఈ ప్రణాళికను ఎవరైనా అనుసరించవచ్చు. మీరు చదివిన అధ్యాయాలను సేవ్ చేయడానికి నమోదు చేసుకోండి లేదా లాగిన్ అవ్వండి.",
    signInCta = "నమోదు / లాగిన్"
)

internal fun bibleStringsFor(language: Language): BibleStrings = when (language) {
    Language.ENGLISH -> english
    Language.TAMIL -> tamil
    Language.TELUGU -> telugu
}
